---

#the id ,the metadata of the item
id: "347:0"

#message
msg-chest-null: "§cThere are no safes around you"
msg-chest: "§cThere are % safes around you" #% = number of chests

#radius chestfinder
radius: 50

#repetition time (chosen 3sec if you have a lot of players)
repeat: 3 #sec
...